services:
  app:
    container_name: foodfy-fastify-app
    build: .
    ports:
      - 3333:3333

  database:
    container_name: foodfy-fastify-postgres
    image: postgres:17.4-alpine3.21
    env_file:
      - .env.development
    ports:
      - 5432:5432
